#
# Copyright (c) Caiden Sanders and his affiliates.
#
# This source tree is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
#

name: DeployAPIToAWS

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  
  #
  # deploy: Deploy the API to AWS EC2 server via SCP
  #
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Test using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      # Install Dependencies (from network)
      - name: Install Dependencies (from network)
        run: |
          yarn install --check-files --force
          yarn --cwd packages/api install --check-files --force
      
      # Build web-frontend into /build directory and gzipper
      - name: Build API and GZIP
        run: |
          yarn --cwd packages/api build
          yarn --cwd packages/api webpack
          
      # Builds TAR in root directory
      - name: Build TAR in Root Directory
        run: |
          cp -TR packages/api/dist/main.js ./main.js
          
      # Stop PM2 main.js
      - name: Stop PM2 main.js
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: pm2 delete main

      # Copy file via SCP and SSH Key to Ubuntu AWS EC2
      - name: Copy file VIA SSH Key to Ubuntu AWS EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "main.js"
          target: "/home/ubuntu/"
          overwrite: true
          
        # Start PM2 main.js
      - name: Start PM2 main.js
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: pm2 start /home/ubuntu/main.js
